//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.App.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntityNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Resources.App.Domain.EntityNames", typeof(EntityNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        public static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App User.
        /// </summary>
        public static string AppUser {
            get {
                return ResourceManager.GetString("AppUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association.
        /// </summary>
        public static string Association {
            get {
                return ResourceManager.GetString("Association", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIll.
        /// </summary>
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fund.
        /// </summary>
        public static string Fund {
            get {
                return ResourceManager.GetString("Fund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility.
        /// </summary>
        public static string Utility {
            get {
                return ResourceManager.GetString("Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility in bill.
        /// </summary>
        public static string UtilityBill {
            get {
                return ResourceManager.GetString("UtilityBill", resourceCulture);
            }
        }
    }
}
